### ISSUE TITLE
Can we replace framework binary as well?

### ISSUE THREAD

**Issue by liuxuan30** [karek314/HandyIPAPatcher#3]
Hi there,

Thanks for the tool! But want to ask can we replace framework binary as well?

tried several times, looks like not able to. or what cmd is right? Thanks

**Comment by karek314** [comment]
Hi @liuxuan30 

`bash extract_thin.sh frameworks` This one will unpack ipa, create app binaries and create directory tmp_framworks which includes fat frameworks and unpacked frameworks.

If you want to edit these, you need to edit thin framework binaries and then if you do 
`bash replace_bin.sh fat` it will automatically reassemble thin framework binaries into fat and pack everything up as it needs to be.

Cheers

**Comment by liuxuan30** [comment]
@karek314 thanks!

I only need 64bit frameworks, so fat binary is not needed. I tried to replace the framework binary in `tmp_framworks` and use 'replace_bin.sh' to repack, but seems it didn't have my framework binary.

I assume replacing binary equals to editing the binary, right?

**Comment by karek314** [comment]
> I assume replacing binary equals to editing the binary, right?

Yes

> Is sh replace_bin.sh enough or I should use bash replace_bin.sh fat all the time?

Depends on original IPA, most of modern IPA's have everything packed as fat, I'd just stick with originals, hence if frameworks are fat, use fat. Edit thin binaries only, as old fat will be delated anyways during repack - https://github.com/karek314/HandyIPAPatcher/blob/master/replace_bin.sh#L50

https://github.com/karek314/HandyIPAPatcher/blob/master/replace_bin.sh#L53
If you correctly modified target thin library, it must work as it packs both thin binaries into fat and place them back in IPA. Perhaps, you modified wrong arch for device you run it on, or modified code does not get executed (?). You can place some dummy crash code in some of initializer methods of framework to test it out.

**Comment by liuxuan30** [comment]
sure thing. Thanks! I will try again.
